### ISSUE TITLE
Comfortable and clean full status report

### ISSUE THREAD

**Issue by arthurpaulino** [arthurpaulino/miraiml#11]
Design a way to display the full status of the engine, if requested:

- Scores
- Ensemble weights
- The description of each base model

Would static html files be enough? Maybe a fancy web app?

**Comment by arthurpaulino** [comment]
Message example:

```json
[
	{
		"id": "Logistic Regression",
		"model_class": "LogisticRegression",
		"parameters": {"solver": "lbfgs", "penalty": "l2"},
		"features": ["feature1", "feature2", "feature3"],
		"score": 0.7
	},
	
	{
		"id": "Gaussian NB",
		"model_class": "GaussianNB",
		"parameters": {},
		"features": ["feature1", "feature3"],
		"score": 0.8
	},
	
	{
		"id": "Ensemble",
		"score": 0.85,
		"weights": {"Gaussian NB": 0.8, "Logistic Regression": 0.2}
	}
]
```

**Comment by bractus** [comment]
Socket.io and python: https://www.youtube.com/watch?v=BSGGAzsgFvk&fbclid=IwAR3X4cqnQ1owd_4VClWcg9eDcmNNHsgZuEIkWjZpWPy5D6cFjLKlBSBYeRs

**Comment by bractus** [comment]
Serverless can be a option: https://martinfowler.com/articles/serverless.html

**Comment by arthurpaulino** [comment]
> Serverless can be a option: https://martinfowler.com/articles/serverless.html

Interesting architecture. But isn't it supposed to work well on large scale apps?

**Comment by arthurpaulino** [comment]
unnecessary for now.

**Comment by arthurpaulino** [comment]
https://github.com/arthurpaulino/miraiml/pull/61
